services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: shippio
      POSTGRES_USER: shippio
      POSTGRES_PASSWORD: shippio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shippio -d shippio"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: yavijit1/shipment-service-app:latest  # Docker Hub image
    container_name: shipment-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev # available profile -> 'dev' or 'prod'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shippio
      SPRING_DATASOURCE_USERNAME: shippio
      SPRING_DATASOURCE_PASSWORD: shippio
      APP_FILE_STORAGE_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

volumes:
  postgres_data:
  uploads_data: